[build]
  command = "node index.js"  
  functions = "functions" 

[[redirects]]
  from = "/api/*"
  to = "/:splat"
  status = 200

[redirects.headers]
Access-Control-Allow-Origin = "http://localhost:8100"
Access-Control-Allow-Methods = "GET, POST, OPTIONS"
Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Accept"

[[redirects]]
  from = "/*"
  to = "/:splat"

[context.production.environment]
  NETLIFY_DB_HOST = "brwyfouxydrilhkclil6-mysql.services.clever-cloud.com"
  NETLIFY_DB_USERNAME = "unfow3ay7ntautmd"
  NETLIFY_DB_PASSWORD = "XiPcIeCVqW30DNLO0994"
  NETLIFY_DB_DBNAME = "brwyfouxydrilhkclil6"
